name: Deploy DiscordBot manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (z. B. v1.0.0)"
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v6

      # Login to GHCR with user: equindar
      - name: Log in to GitHub Container Registry
        run: |
          docker login --username equindar --password ${{ secrets.GH_PAT }} ghcr.io

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -f apps/bot/Dockerfile \
            --build-arg NODE_ENV=production \
            -t ghcr.io/equindar/${{ vars.APPS_BOT_IMAGE_NAME }}:${{ github.event.inputs.version }} \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/equindar/${{ vars.APPS_BOT_IMAGE_NAME }}:${{ github.event.inputs.version }}
